# Generated by Django 3.1.7 on 2023-03-11 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_tctip', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tip',
            options={'managed': False, 'verbose_name': '公告栏', 'verbose_name_plural': '公告栏'},
        ),
    ]
