# Generated by Django 2.2.27 on 2023-03-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbnormalRecords',
            fields=[
                ('handle', models.CharField(primary_key=True, db_column=' HANDLE', max_length=255)),
                ('location_c', models.CharField(db_column='LOCATION_C', max_length=255)),
                ('temperature', models.CharField(blank=True, db_column='TEMPERATURE', max_length=255, null=True)),
                ('student_num', models.CharField(db_column='STUDENT_NUM', max_length=255)),
                ('location_p', models.CharField(db_column='LOCATION_P', max_length=255)),
                ('creation_time', models.DateTimeField(db_column='CREATION_TIME')),
                ('abnormal_type', models.CharField(db_column='ABNORMAL_TYPE', max_length=255)),
                ('abnormal_desc', models.CharField(db_column='ABNORMAL_DESC', max_length=255)),
                ('bts_record', models.CharField(db_column='BTS_RECORD', max_length=255)),
            ],
            options={
                'db_table': 'abnormal_records',
                'managed': False,
            },
        ),
    ]
