# Generated by Django 3.2.18 on 2023-03-11 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abnormal_records', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abnormalrecords',
            options={'managed': False, 'verbose_name': '上报异常维护', 'verbose_name_plural': '上报异常维护'},
        ),
    ]
